from __future__ import annotations

from dataclasses import dataclass

from image_search.constants.colors import COLOR_WORDS, normalize_color_label


@dataclass(frozen=True, slots=True)
class ConceptDefinition:
    key: str
    layer: str
    facet_key: str
    value_key: str
    display: str
    allowed_item_types: tuple[str, ...]
    patterns: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()
    preferred_evidence: str = "both"
    base_confidence: float = 0.76
    multi_value: bool = False
    max_values: int = 1
    search_only: bool = False
    is_filterable: bool = True


@dataclass(frozen=True, slots=True)
class ExtractionRule:
    name: str
    allowed_item_types: tuple[str, ...]
    patterns: tuple[str, ...]
    concept_keys: tuple[str, ...]
    preferred_evidence: str = "both"
    score_bonus: float = 0.1


def _concept(
    facet_key: str,
    value_key: str,
    display: str,
    *,
    allowed_item_types: tuple[str, ...],
    patterns: tuple[str, ...],
    preferred_evidence: str = "both",
    base_confidence: float = 0.76,
    multi_value: bool = False,
    max_values: int = 1,
    search_only: bool = False,
    is_filterable: bool | None = None,
    aliases: tuple[str, ...] = (),
) -> ConceptDefinition:
    return ConceptDefinition(
        key=f"{facet_key}:{value_key}",
        layer="visual",
        facet_key=facet_key,
        value_key=value_key,
        display=display,
        allowed_item_types=allowed_item_types,
        patterns=patterns,
        aliases=aliases,
        preferred_evidence=preferred_evidence,
        base_confidence=base_confidence,
        multi_value=multi_value,
        max_values=max_values,
        search_only=search_only,
        is_filterable=(not search_only) if is_filterable is None else is_filterable,
    )


def _rule(
    name: str,
    *,
    allowed_item_types: tuple[str, ...],
    patterns: tuple[str, ...],
    concept_keys: tuple[str, ...],
    preferred_evidence: str = "both",
    score_bonus: float = 0.1,
) -> ExtractionRule:
    return ExtractionRule(
        name=name,
        allowed_item_types=allowed_item_types,
        patterns=patterns,
        concept_keys=concept_keys,
        preferred_evidence=preferred_evidence,
        score_bonus=score_bonus,
    )


ALL_ITEM_TYPES: tuple[str, ...] = (
    "hair",
    "outerwear",
    "tops",
    "bottoms",
    "socks",
    "shoes",
    "hairAccessories",
    "headwear",
    "earrings",
    "neckwear",
    "bracelets",
    "chokers",
    "gloves",
    "handhelds",
    "bodyPaint",
    "baseMakeup",
    "eyebrows",
    "eyelashes",
    "contactLenses",
    "lips",
    "skinTones",
    "dresses",
    "faceDecorations",
    "chestAccessories",
    "pendants",
    "backpieces",
    "rings",
    "armDecorations",
    "fullMakeup",
    "abilityHandhelds",
    "unknown",
)

ACCESSORY_OR_PROP_TYPES: tuple[str, ...] = (
    "headwear",
    "hairAccessories",
    "handhelds",
    "abilityHandhelds",
    "backpieces",
    "chestAccessories",
    "pendants",
)

GARMENT_TYPES: tuple[str, ...] = ("outerwear", "tops", "dresses", "bottoms", "shoes", "socks")


def _color_concepts() -> list[ConceptDefinition]:
    values = sorted({normalize_color_label(value) for value in COLOR_WORDS} | {"multicolor"})
    concepts: list[ConceptDefinition] = []
    for facet_key in ("color.primary", "color.secondary"):
        for value in values:
            concepts.append(
                ConceptDefinition(
                    key=f"{facet_key}:{value}",
                    layer="visual",
                    facet_key=facet_key,
                    value_key=value,
                    display=value.replace("_", " "),
                    allowed_item_types=ALL_ITEM_TYPES,
                    preferred_evidence="cv_only",
                    base_confidence=0.9,
                )
            )
    return concepts


VISUAL_CONCEPTS: list[ConceptDefinition] = [
    *_color_concepts(),
    _concept(
        "pattern",
        "lace",
        "lace",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\blace(?: trim)?\b",),
        multi_value=True,
        max_values=2,
        base_confidence=0.82,
    ),
    _concept(
        "pattern",
        "plaid",
        "plaid",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bplaid\b", r"\btartan\b"),
        multi_value=True,
        max_values=2,
        base_confidence=0.82,
    ),
    _concept(
        "pattern",
        "striped",
        "striped",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bstriped?\b", r"\bstripes?\b"),
        multi_value=True,
        max_values=2,
        base_confidence=0.8,
    ),
    _concept(
        "pattern",
        "checkered",
        "checkered",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bcheck(?:ered)?\b", r"\bgingham\b"),
        multi_value=True,
        max_values=2,
        base_confidence=0.81,
    ),
    _concept(
        "pattern",
        "floral",
        "floral",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bfloral\b", r"\bflowers?\b", r"\bflower print\b"),
        multi_value=True,
        max_values=2,
        base_confidence=0.82,
    ),
    _concept(
        "motif",
        "bow",
        "bow",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bbow\b", r"\bbows\b"),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.84,
    ),
    _concept(
        "motif",
        "ribbon",
        "ribbon",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bribbon\b", r"\bribbons\b"),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "motif",
        "flower",
        "flower",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bflowers?\b", r"\bfloral applique\b"),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "motif",
        "butterfly",
        "butterfly",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bbutterfly\b", r"\bbutterflies\b"),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "motif",
        "star",
        "star",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bstars?\b",),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.79,
    ),
    _concept(
        "motif",
        "heart",
        "heart",
        allowed_item_types=ALL_ITEM_TYPES,
        patterns=(r"\bhearts?\b",),
        multi_value=True,
        max_values=3,
        preferred_evidence="icon",
        base_confidence=0.79,
    ),
    _concept(
        "motif",
        "wings",
        "wings",
        allowed_item_types=("backpieces", "headwear", "hairAccessories"),
        patterns=(r"\bwings?\b",),
        multi_value=True,
        max_values=2,
        preferred_evidence="overview",
        base_confidence=0.83,
    ),
    _concept(
        "hair.length",
        "short",
        "short hair",
        allowed_item_types=("hair",),
        patterns=(r"\bshort hair\b", r"\bbob(?: cut)?\b",),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "hair.length",
        "medium",
        "medium hair",
        allowed_item_types=("hair",),
        patterns=(r"\bshoulder[- ]length hair\b", r"\bmedium(?:-length)? hair\b"),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "hair.length",
        "long",
        "long hair",
        allowed_item_types=("hair",),
        patterns=(r"\blong hair\b", r"\bfalls over (?:the )?shoulders\b", r"\bcascad(?:e|es|ing) down\b"),
        preferred_evidence="overview",
        base_confidence=0.86,
    ),
    _concept(
        "hair.structure",
        "twin_tails",
        "twin tails",
        allowed_item_types=("hair",),
        patterns=(r"\btwin tails?\b", r"\bpigtails?\b", r"\btwo (?:large )?pigtails\b"),
        preferred_evidence="overview",
        multi_value=True,
        max_values=2,
        base_confidence=0.88,
    ),
    _concept(
        "hair.structure",
        "half_up",
        "half up",
        allowed_item_types=("hair",),
        patterns=(r"\bhalf[- ]up(?:,? half[- ]down)?\b", r"\bhalf-down look\b"),
        preferred_evidence="overview",
        multi_value=True,
        max_values=2,
        base_confidence=0.86,
    ),
    _concept(
        "hair.structure",
        "ponytail",
        "ponytail",
        allowed_item_types=("hair",),
        patterns=(r"\bponytail\b", r"\bhigh ponytail\b"),
        preferred_evidence="overview",
        multi_value=True,
        max_values=2,
        base_confidence=0.8,
    ),
    _concept(
        "hair.structure",
        "braid",
        "braid",
        allowed_item_types=("hair",),
        patterns=(r"\bbraid(?:ed)?\b",),
        preferred_evidence="icon",
        multi_value=True,
        max_values=2,
        base_confidence=0.72,
    ),
    _concept(
        "hair.structure",
        "bun",
        "bun",
        allowed_item_types=("hair",),
        patterns=(r"\bbun\b",),
        preferred_evidence="overview",
        multi_value=True,
        max_values=2,
        base_confidence=0.8,
    ),
    _concept(
        "dresses.silhouette",
        "a_line",
        "A-line",
        allowed_item_types=("dresses",),
        patterns=(r"\ba[- ]line\b",),
        preferred_evidence="overview",
        base_confidence=0.86,
    ),
    _concept(
        "dresses.silhouette",
        "ballgown",
        "ballgown",
        allowed_item_types=("dresses",),
        patterns=(r"\bballgown\b", r"\bball gown\b", r"\bgown\b"),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "dresses.length",
        "mini",
        "mini",
        allowed_item_types=("dresses",),
        patterns=(r"\bmini dress\b", r"\bshort dress\b", r"\babove the knee\b"),
        preferred_evidence="overview",
        base_confidence=0.83,
    ),
    _concept(
        "dresses.length",
        "midi",
        "midi",
        allowed_item_types=("dresses",),
        patterns=(r"\bmidi dress\b", r"\bbelow the knee\b", r"\bmid-calf\b"),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "dresses.length",
        "maxi",
        "maxi",
        allowed_item_types=("dresses",),
        patterns=(r"\bmaxi dress\b", r"\bfloor-length\b", r"\blong dress\b"),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "shoes.subtype",
        "boots",
        "boots",
        allowed_item_types=("shoes",),
        patterns=(r"\bboots?\b", r"\bankle boots?\b", r"\bknee[- ]high boots?\b"),
        preferred_evidence="overview",
        base_confidence=0.87,
    ),
    _concept(
        "shoes.subtype",
        "heels",
        "heels",
        allowed_item_types=("shoes",),
        patterns=(r"\bheels?\b", r"\bhigh heels?\b", r"\bpumps?\b"),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "shoes.subtype",
        "sneakers",
        "sneakers",
        allowed_item_types=("shoes",),
        patterns=(r"\bsneakers?\b", r"\btrainers?\b"),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "shoes.subtype",
        "sandals",
        "sandals",
        allowed_item_types=("shoes",),
        patterns=(r"\bsandals?\b",),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "shoes.subtype",
        "flats",
        "flats",
        allowed_item_types=("shoes",),
        patterns=(r"\bflats?\b", r"\bballet flats?\b"),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "tops.subtype",
        "jacket",
        "jacket",
        allowed_item_types=("tops",),
        patterns=(r"\bjacket\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "tops.subtype",
        "cardigan",
        "cardigan",
        allowed_item_types=("tops",),
        patterns=(r"\bcardigan\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "tops.subtype",
        "vest",
        "vest",
        allowed_item_types=("tops",),
        patterns=(r"\bvest\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "tops.subtype",
        "blazer",
        "blazer",
        allowed_item_types=("tops",),
        patterns=(r"\bblazer\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "tops.subtype",
        "shirt",
        "shirt",
        allowed_item_types=("tops",),
        patterns=(r"\bshirt\b", r"\bbutton[- ]up shirt\b"),
        preferred_evidence="overview",
        base_confidence=0.78,
    ),
    _concept(
        "tops.subtype",
        "blouse",
        "blouse",
        allowed_item_types=("tops",),
        patterns=(r"\bblouse\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "tops.subtype",
        "sweater",
        "sweater",
        allowed_item_types=("tops",),
        patterns=(r"\bsweater\b", r"\bjumper\b", r"\bknit top\b"),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "tops.subtype",
        "camisole",
        "camisole",
        allowed_item_types=("tops",),
        patterns=(r"\bcamisole\b", r"\bcami\b"),
        preferred_evidence="overview",
        base_confidence=0.79,
    ),
    _concept(
        "tops.subtype",
        "halter",
        "halter top",
        allowed_item_types=("tops",),
        patterns=(r"\bhalter(?: top)?\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "tops.subtype",
        "corset",
        "corset",
        allowed_item_types=("tops",),
        patterns=(r"\bcorset\b", r"\bbustier\b"),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "outerwear.subtype",
        "coat",
        "coat",
        allowed_item_types=("outerwear",),
        patterns=(r"\bcoat\b",),
        preferred_evidence="overview",
        base_confidence=0.85,
    ),
    _concept(
        "outerwear.subtype",
        "cape",
        "cape",
        allowed_item_types=("outerwear",),
        patterns=(r"\bcape\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "outerwear.subtype",
        "cloak",
        "cloak",
        allowed_item_types=("outerwear",),
        patterns=(r"\bcloak\b",),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "outerwear.subtype",
        "shawl",
        "shawl",
        allowed_item_types=("outerwear",),
        patterns=(r"\bshawl\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "outerwear.subtype",
        "hooded_jacket",
        "hooded jacket",
        allowed_item_types=("outerwear",),
        patterns=(r"\bhooded jacket\b", r"\bhoodie\b"),
        preferred_evidence="overview",
        base_confidence=0.81,
    ),
    _concept(
        "outerwear.subtype",
        "bolero",
        "bolero",
        allowed_item_types=("outerwear",),
        patterns=(r"\bbolero\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
    ),
    _concept(
        "tops.neckline",
        "v_neck",
        "V-neckline",
        allowed_item_types=("tops",),
        patterns=(r"\bv-neck(?:line)?\b",),
        preferred_evidence="overview",
        base_confidence=0.77,
        search_only=True,
    ),
    _concept(
        "tops.neckline",
        "round_neck",
        "round neckline",
        allowed_item_types=("tops",),
        patterns=(r"\bround neck(?:line)?\b", r"\bcrew neck\b"),
        preferred_evidence="overview",
        base_confidence=0.75,
        search_only=True,
    ),
    _concept(
        "tops.neckline",
        "high_neck",
        "high neckline",
        allowed_item_types=("tops",),
        patterns=(r"\bhigh neck(?:line)?\b", r"\bhigh collar\b"),
        preferred_evidence="overview",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "tops.neckline",
        "collared",
        "collared",
        allowed_item_types=("tops",),
        patterns=(r"\bcollar(?:ed)?\b",),
        preferred_evidence="icon",
        base_confidence=0.72,
        search_only=True,
    ),
    _concept(
        "tops.collar",
        "ruffled_collar",
        "ruffled collar",
        allowed_item_types=("tops",),
        patterns=(r"\bruffled collar\b", r"\bfrilled collar\b"),
        preferred_evidence="icon",
        base_confidence=0.77,
        search_only=True,
    ),
    _concept(
        "tops.collar",
        "high_collar",
        "high collar",
        allowed_item_types=("tops",),
        patterns=(r"\bhigh collar\b",),
        preferred_evidence="icon",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "tops.closure",
        "button_down",
        "button-down front",
        allowed_item_types=("tops",),
        patterns=(r"\bbutton[- ]down(?: front)?\b", r"\bbuttons?\b"),
        preferred_evidence="icon",
        base_confidence=0.78,
        search_only=True,
    ),
    _concept(
        "tops.closure",
        "zipper",
        "zipper front",
        allowed_item_types=("tops",),
        patterns=(r"\bzipper\b", r"\bzipped\b"),
        preferred_evidence="icon",
        base_confidence=0.78,
        search_only=True,
    ),
    _concept(
        "tops.closure",
        "tied_front",
        "tied front",
        allowed_item_types=("tops",),
        patterns=(r"\btied front\b", r"\bfront tie\b", r"\bbow tie front\b"),
        preferred_evidence="icon",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "tops.sleeve_style",
        "long_sleeve",
        "long sleeves",
        allowed_item_types=("tops",),
        patterns=(r"\blong sleeves?\b",),
        preferred_evidence="overview",
        base_confidence=0.75,
        search_only=True,
    ),
    _concept(
        "tops.sleeve_style",
        "short_sleeve",
        "short sleeves",
        allowed_item_types=("tops",),
        patterns=(r"\bshort sleeves?\b",),
        preferred_evidence="overview",
        base_confidence=0.75,
        search_only=True,
    ),
    _concept(
        "tops.sleeve_style",
        "sleeveless",
        "sleeveless",
        allowed_item_types=("tops",),
        patterns=(r"\bsleeveless\b",),
        preferred_evidence="overview",
        base_confidence=0.8,
        search_only=True,
    ),
    _concept(
        "tops.sleeve_style",
        "puff_sleeve",
        "puff sleeves",
        allowed_item_types=("tops",),
        patterns=(r"\bpuff(?:ed)? sleeves?\b",),
        preferred_evidence="overview",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "tops.sleeve_style",
        "flared_sleeve",
        "flared sleeves",
        allowed_item_types=("tops",),
        patterns=(r"\bflared sleeves?\b", r"\bbell sleeves?\b"),
        preferred_evidence="overview",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "outerwear.closure",
        "button_down",
        "button-down front",
        allowed_item_types=("outerwear",),
        patterns=(r"\bbutton[- ]down(?: front)?\b", r"\bbuttons?\b"),
        preferred_evidence="icon",
        base_confidence=0.78,
        search_only=True,
    ),
    _concept(
        "outerwear.closure",
        "zipper",
        "zipper front",
        allowed_item_types=("outerwear",),
        patterns=(r"\bzipper\b", r"\bzipped\b"),
        preferred_evidence="icon",
        base_confidence=0.78,
        search_only=True,
    ),
    _concept(
        "outerwear.closure",
        "tied_front",
        "tied front",
        allowed_item_types=("outerwear",),
        patterns=(r"\btied front\b", r"\bfront tie\b"),
        preferred_evidence="icon",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "outerwear.collar",
        "high_collar",
        "high collar",
        allowed_item_types=("outerwear",),
        patterns=(r"\bhigh collar\b",),
        preferred_evidence="icon",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "outerwear.collar",
        "ruffled_collar",
        "ruffled collar",
        allowed_item_types=("outerwear",),
        patterns=(r"\bruffled collar\b", r"\bfrilled collar\b"),
        preferred_evidence="icon",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "outerwear.collar",
        "hooded",
        "hooded",
        allowed_item_types=("outerwear",),
        patterns=(r"\bhood(?:ed)?\b",),
        preferred_evidence="overview",
        base_confidence=0.76,
        search_only=True,
    ),
    _concept(
        "headwear.subtype",
        "hat",
        "hat",
        allowed_item_types=("headwear",),
        patterns=(r"\bhat\b", r"\bcap\b", r"\bbonnet\b", r"\bberet\b"),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "headwear.subtype",
        "crown",
        "crown",
        allowed_item_types=("headwear",),
        patterns=(r"\bcrown\b", r"\btiara\b"),
        preferred_evidence="icon",
        base_confidence=0.85,
    ),
    _concept(
        "headwear.subtype",
        "veil",
        "veil",
        allowed_item_types=("headwear",),
        patterns=(r"\bveil\b",),
        preferred_evidence="overview",
        base_confidence=0.84,
    ),
    _concept(
        "headwear.subtype",
        "hood",
        "hood",
        allowed_item_types=("headwear",),
        patterns=(r"\bhood\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "hairAccessories.subtype",
        "headband",
        "headband",
        allowed_item_types=("hairAccessories",),
        patterns=(r"\bheadband\b",),
        preferred_evidence="icon",
        base_confidence=0.85,
    ),
    _concept(
        "hairAccessories.subtype",
        "hairpin",
        "hairpin",
        allowed_item_types=("hairAccessories",),
        patterns=(r"\bhair ?pin\b", r"\bclip\b", r"\bbarrette\b"),
        preferred_evidence="icon",
        base_confidence=0.82,
    ),
    _concept(
        "hairAccessories.subtype",
        "bow",
        "hair bow",
        allowed_item_types=("hairAccessories",),
        patterns=(r"\bbow\b", r"\bribbon\b"),
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "hairAccessories.subtype",
        "crown",
        "hair crown",
        allowed_item_types=("hairAccessories",),
        patterns=(r"\bcrown\b", r"\btiara\b"),
        preferred_evidence="icon",
        base_confidence=0.82,
    ),
    _concept(
        "handhelds.subtype",
        "bag",
        "bag",
        allowed_item_types=("handhelds", "abilityHandhelds"),
        patterns=(r"\bbag\b", r"\bpurse\b"),
        preferred_evidence="icon",
        base_confidence=0.83,
    ),
    _concept(
        "handhelds.subtype",
        "fan",
        "fan",
        allowed_item_types=("handhelds", "abilityHandhelds"),
        patterns=(r"\bfan\b",),
        preferred_evidence="icon",
        base_confidence=0.83,
    ),
    _concept(
        "handhelds.subtype",
        "umbrella",
        "umbrella",
        allowed_item_types=("handhelds", "abilityHandhelds"),
        patterns=(r"\bumbrella\b", r"\bparasol\b"),
        preferred_evidence="icon",
        base_confidence=0.84,
    ),
    _concept(
        "handhelds.subtype",
        "book",
        "book",
        allowed_item_types=("handhelds", "abilityHandhelds"),
        patterns=(r"\bbook\b",),
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "handhelds.subtype",
        "basket",
        "basket",
        allowed_item_types=("handhelds",),
        patterns=(r"\bbasket\b",),
        preferred_evidence="icon",
        base_confidence=0.82,
    ),
    _concept(
        "handhelds.subtype",
        "lantern",
        "lantern",
        allowed_item_types=("handhelds", "abilityHandhelds"),
        patterns=(r"\blantern\b",),
        preferred_evidence="icon",
        base_confidence=0.83,
    ),
    _concept(
        "handhelds.subtype",
        "bouquet",
        "bouquet",
        allowed_item_types=("handhelds",),
        patterns=(r"\bbouquet\b", r"\bflowers?\b"),
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "handhelds.subtype",
        "plush",
        "plush",
        allowed_item_types=("handhelds",),
        patterns=(r"\bplush\b", r"\bstuffed\b"),
        preferred_evidence="icon",
        base_confidence=0.8,
    ),
    _concept(
        "handhelds.subtype",
        "staff",
        "staff",
        allowed_item_types=("abilityHandhelds",),
        patterns=(r"\bstaff\b", r"\bwand\b", r"\bscepter\b"),
        preferred_evidence="icon",
        base_confidence=0.82,
    ),
    _concept(
        "backpieces.subtype",
        "wings",
        "wings",
        allowed_item_types=("backpieces",),
        patterns=(r"\bwings?\b",),
        preferred_evidence="overview",
        base_confidence=0.86,
    ),
    _concept(
        "backpieces.subtype",
        "backpack",
        "backpack",
        allowed_item_types=("backpieces",),
        patterns=(r"\bbackpack\b", r"\bpack\b"),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "backpieces.subtype",
        "tail",
        "tail",
        allowed_item_types=("backpieces",),
        patterns=(r"\btail\b",),
        preferred_evidence="overview",
        base_confidence=0.82,
    ),
    _concept(
        "backpieces.subtype",
        "cape",
        "cape backpiece",
        allowed_item_types=("backpieces",),
        patterns=(r"\bcape\b",),
        preferred_evidence="overview",
        base_confidence=0.78,
    ),
]

TAXONOMY_CONCEPTS: tuple[ConceptDefinition, ...] = tuple(VISUAL_CONCEPTS)
CONCEPT_BY_KEY: dict[str, ConceptDefinition] = {definition.key: definition for definition in TAXONOMY_CONCEPTS}
VISUAL_CONCEPTS_BY_TYPE: dict[str, tuple[ConceptDefinition, ...]] = {
    item_type: tuple(
        definition
        for definition in TAXONOMY_CONCEPTS
        if item_type in definition.allowed_item_types
    )
    for item_type in ALL_ITEM_TYPES
}

TERM_EXTRACTION_RULES: tuple[ExtractionRule, ...] = (
    _rule(
        "tops_bow_collar",
        allowed_item_types=("tops",),
        patterns=(r"\bcollar is tied in a bow\b", r"\bneck(?:line)? is tied in a bow\b"),
        concept_keys=("motif:bow", "tops.neckline:collared"),
        preferred_evidence="icon",
        score_bonus=0.12,
    ),
    _rule(
        "tops_bow_neckline",
        allowed_item_types=("tops",),
        patterns=(r"\bbow at the neckline\b", r"\bbow on the neckline\b"),
        concept_keys=("motif:bow",),
        preferred_evidence="overview",
        score_bonus=0.1,
    ),
    _rule(
        "tops_button_front",
        allowed_item_types=("tops",),
        patterns=(r"\bbuttons? down the front\b", r"\bbuttons? on the front\b"),
        concept_keys=("tops.closure:button_down",),
        preferred_evidence="icon",
        score_bonus=0.12,
    ),
    _rule(
        "tops_front_tie",
        allowed_item_types=("tops",),
        patterns=(r"\btied front\b", r"\bfront tie\b", r"\bbow tie front\b"),
        concept_keys=("tops.closure:tied_front",),
        preferred_evidence="icon",
        score_bonus=0.12,
    ),
    _rule(
        "tops_striped_sleeves",
        allowed_item_types=("tops",),
        patterns=(r"\blong sleeves? with .*stripes?\b", r"\bstripes? on the sleeves\b"),
        concept_keys=("tops.sleeve_style:long_sleeve", "pattern:striped"),
        preferred_evidence="overview",
        score_bonus=0.12,
    ),
    _rule(
        "tops_checkered_halter",
        allowed_item_types=("tops",),
        patterns=(r"\bcheck(?:ered)? halter top\b",),
        concept_keys=("pattern:checkered", "tops.subtype:halter"),
        preferred_evidence="overview",
        score_bonus=0.12,
    ),
    _rule(
        "tops_ruffled_collar",
        allowed_item_types=("tops",),
        patterns=(r"\bruffled collar\b", r"\bfrilled collar\b"),
        concept_keys=("tops.collar:ruffled_collar", "tops.neckline:collared"),
        preferred_evidence="icon",
        score_bonus=0.1,
    ),
    _rule(
        "tops_high_collar",
        allowed_item_types=("tops",),
        patterns=(r"\bhigh collar\b",),
        concept_keys=("tops.collar:high_collar", "tops.neckline:collared"),
        preferred_evidence="icon",
        score_bonus=0.1,
    ),
    _rule(
        "outerwear_striped_sleeves",
        allowed_item_types=("outerwear",),
        patterns=(r"\blong sleeves? with .*stripes?\b", r"\bstripes? on the sleeves\b"),
        concept_keys=("pattern:striped",),
        preferred_evidence="overview",
        score_bonus=0.1,
    ),
    _rule(
        "outerwear_button_front",
        allowed_item_types=("outerwear",),
        patterns=(r"\bbuttons? down the front\b", r"\bbuttons? on the front\b"),
        concept_keys=("outerwear.closure:button_down",),
        preferred_evidence="icon",
        score_bonus=0.12,
    ),
    _rule(
        "outerwear_front_tie",
        allowed_item_types=("outerwear",),
        patterns=(r"\btied front\b", r"\bfront tie\b"),
        concept_keys=("outerwear.closure:tied_front",),
        preferred_evidence="icon",
        score_bonus=0.12,
    ),
    _rule(
        "outerwear_ruffled_collar",
        allowed_item_types=("outerwear",),
        patterns=(r"\bruffled collar\b", r"\bfrilled collar\b"),
        concept_keys=("outerwear.collar:ruffled_collar",),
        preferred_evidence="icon",
        score_bonus=0.1,
    ),
    _rule(
        "outerwear_high_collar",
        allowed_item_types=("outerwear",),
        patterns=(r"\bhigh collar\b",),
        concept_keys=("outerwear.collar:high_collar",),
        preferred_evidence="icon",
        score_bonus=0.1,
    ),
)

TERM_EXTRACTION_RULES_BY_TYPE: dict[str, tuple[ExtractionRule, ...]] = {
    item_type: tuple(
        rule
        for rule in TERM_EXTRACTION_RULES
        if item_type in rule.allowed_item_types
    )
    for item_type in ALL_ITEM_TYPES
}
